name: Build, publish and release
on:
  workflow_call:
    inputs:
      java_version:
        type: string
        default: "17"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current

      - name: Build with Gradle
        run: gradle build

      - name: Publish to GitHub package registry
        run: gradle publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create a release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gradle -q printChangeLog | gh release create ${{ github.ref_name }} build/libs/*.jar build/launch4j/*.exe -F -
