name: Build, publish and release
on:
  push:
    tags:
      - v*.*.*  # only on release tags

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current

      - name: Build with Gradle
        run: gradle build

      - name: Publish to GitHub package registry
        run: gradle publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create a release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gradle -q printChangeLog | gh release create ${{ github.ref_name }} build/libs/*.jar -F -
